spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringCloud_sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: admin
  rabbitmq:
    host: 192.168.0.110
    port: 5672
    username: guest
    password: guest
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.example.order.domain
env:
  dev5
